[project]
name = "{{ project.name }}"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "polars>=1.32.3",
    "scikit-learn>=1.7.1",
]

[dependency-groups]
dev = [
    "bandit>=1.8.6",
    "pytest>=8.4.1",
    "ruff>=0.12.9",
    "ty>=0.0.1a19",
]
